apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zm1edpagv-python
  janus-idp.io/tekton: zm1edpagv-python
  backstage.io/kubernetes-id: zm1edpagv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zm1edpagv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
